### ISSUE TITLE
Modifica gestione versioni build

### ISSUE THREAD

**Issue by frbellomi** [mitechsrl/onit-cli#1]
Proposta:
- La gestione delle versioni patch/minor/major deve risultare disponibile solo per le build produttive
- Le build uat/beta.... devono proporre solo il relativo suffisso e un contatore successivo

Motivo:
Tutte le branch partono dalla master, di conseguenza una beta o un uat rappresentano una 'uscita' di quella relativa versione/patch

**Comment by ivanvaccari** [comment]
Questa issue è ancora valida? Mi sembra avessimo verificato questa cosa
